### ISSUE TITLE
unicode ascii error

### ISSUE THREAD

**Issue by xellosiris** [nagadit/DeepFaceLab_Linux#13]
when I tried to training model, it occurred an error:(system Ubutun)
Error: 'ascii' codec can't encode character '\u200b' in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/root/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/root/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 162, in __init__
    nn.initialize(self.device_config)
  File "/root/DeepFaceLab_Linux/DeepFaceLab/core/leras/nn.py", line 73, in initialize
    os.environ['CUDA_​CACHE_​MAXSIZE'] = '536870912' #512Mb (32mb default)
  File "/root/anaconda3/envs/deepfacelab/lib/python3.6/os.py", line 673, in __setitem__
    key = self.encodekey(key)
  File "/root/anaconda3/envs/deepfacelab/lib/python3.6/os.py", line 745, in encode
    return value.encode(encoding, 'surrogateescape')
UnicodeEncodeError: 'ascii' codec can't encode character '\u200b' in position 5: ordinal not in range(128)

**Comment by xellosiris** [comment]
I sloved

**Comment by nagadit** [comment]
@xellosiris 
describe how you solved the problem for others and close this issue

**Comment by Seanseattle** [comment]
Hello, I have met the same problem. Could you tell me how to fix it?
