### ISSUE TITLE
Deepfacelab not utilizing GPU, failing, even though all depencencies fulfilled, python sees GPU

### ISSUE THREAD

**Issue by Crashhop** [nagadit/DeepFaceLab_Linux#19]
I am having a problem that I cannot seem to pin down. When running the trainer script, I am asked to select a GPU, which I do, so Deepfacelab clearly sees it, but then the whole thing bails out saying it cannot assign a device. Below is the output.

./6_train_SAEHD.sh

Running trainer.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : DF-UD256 - latest
 : 
0
Loading DF-UD256_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1660 Ti

[0] Which GPU indexes to choose? : 
0

Initializing models:   0%|                                                                    | 0/7 [00:00<?, ?it/s]
Error: Cannot assign a device for operation encoder/down1/downs_0/conv1/weight/Initializer/_cai_: Could not satisfy explicit device specification '' because the node node encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (defined at run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py:13) placed on device Device assignments active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation:
  with tf.device(None): </home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:1796>
  with tf.device(/GPU:0): </run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py:233>  was colocated with a group of nodes that required incompatible device '/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Identity: CPU XLA_CPU 
VariableV2: CPU 
Const: CPU XLA_CPU 
Assign: CPU 
Fill: CPU XLA_CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/shape_as_tensor (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/Const (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (Fill) 
  encoder/down1/downs_0/conv1/weight (VariableV2) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/Assign (Assign) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/read (Identity) /device:GPU:0
  Assign_1 (Assign) /device:GPU:0
  Assign_260 (Assign) /device:GPU:0

	 [[node encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (defined at run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py:13) ]]Additional information about colocations:No node-device colocations were active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation.
Device assignments active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation:
  with tf.device(None): </home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:1796>
  with tf.device(/GPU:0): </run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py:233>

Original stack trace for 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_':
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 236, in on_initialize
    encoder_out_ch = self.encoder.compute_output_channels ( (nn.floatx, bgr_shape))
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 147, in compute_output_channels
    shape = self.compute_output_shape(shapes)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 121, in compute_output_shape
    self.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 35, in _build_sub
    layer.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 20, in _build_sub
    self._build_sub(sublayer, f"{name}_{i}")
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 35, in _build_sub
    layer.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 33, in _build_sub
    layer.build_weights()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py", line 76, in build_weights
    self.weight = tf.get_variable("weight", (self.kernel_size,self.kernel_size,self.in_ch,self.out_ch), dtype=self.dtype, initializer=kernel_initializer, trainable=self.trainable )
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1572, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1315, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 569, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 521, in _true_getter
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 940, in _get_single_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2613, in default_variable_creator
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1668, in __init__
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1798, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 909, in <lambda>
    partition_info=partition_info)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py", line 13, in __call__
    return tf.zeros( shape, dtype=dtype, name="_cai_")
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2747, in wrapped
    tensor = fun(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2806, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 239, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3412, in fill
    "Fill", dims=dims, value=value, name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _run_fn
    self._extend_graph()
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1388, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation encoder/down1/downs_0/conv1/weight/Initializer/_cai_: Could not satisfy explicit device specification '' because the node {{colocation_node encoder/down1/downs_0/conv1/weight/Initializer/_cai_}} was colocated with a group of nodes that required incompatible device '/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Identity: CPU XLA_CPU 
VariableV2: CPU 
Const: CPU XLA_CPU 
Assign: CPU 
Fill: CPU XLA_CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/shape_as_tensor (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/Const (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (Fill) 
  encoder/down1/downs_0/conv1/weight (VariableV2) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/Assign (Assign) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/read (Identity) /device:GPU:0
  Assign_1 (Assign) /device:GPU:0
  Assign_260 (Assign) /device:GPU:0

	 [[{{node encoder/down1/downs_0/conv1/weight/Initializer/_cai_}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "/run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 568, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "/run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Saveable.py", line 96, in load_weights
    nn.batch_set_value(tuples)
  File "/run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py", line 29, in batch_set_value
    nn.tf_sess.run(assign_ops, feed_dict=feed_dict)
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation encoder/down1/downs_0/conv1/weight/Initializer/_cai_: Could not satisfy explicit device specification '' because the node node encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (defined at run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py:13) placed on device Device assignments active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation:
  with tf.device(None): </home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:1796>
  with tf.device(/GPU:0): </run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py:233>  was colocated with a group of nodes that required incompatible device '/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Identity: CPU XLA_CPU 
VariableV2: CPU 
Const: CPU XLA_CPU 
Assign: CPU 
Fill: CPU XLA_CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/shape_as_tensor (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_/Const (Const) 
  encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (Fill) 
  encoder/down1/downs_0/conv1/weight (VariableV2) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/Assign (Assign) /device:GPU:0
  encoder/down1/downs_0/conv1/weight/read (Identity) /device:GPU:0
  Assign_1 (Assign) /device:GPU:0
  Assign_260 (Assign) /device:GPU:0

	 [[node encoder/down1/downs_0/conv1/weight/Initializer/_cai_ (defined at run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py:13) ]]Additional information about colocations:No node-device colocations were active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation.
Device assignments active during op 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_' creation:
  with tf.device(None): </home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:1796>
  with tf.device(/GPU:0): </run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py:233>

Original stack trace for 'encoder/down1/downs_0/conv1/weight/Initializer/_cai_':
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 236, in on_initialize
    encoder_out_ch = self.encoder.compute_output_channels ( (nn.floatx, bgr_shape))
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 147, in compute_output_channels
    shape = self.compute_output_shape(shapes)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 121, in compute_output_shape
    self.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 35, in _build_sub
    layer.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 20, in _build_sub
    self._build_sub(sublayer, f"{name}_{i}")
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 35, in _build_sub
    layer.build()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 33, in _build_sub
    layer.build_weights()
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py", line 76, in build_weights
    self.weight = tf.get_variable("weight", (self.kernel_size,self.kernel_size,self.in_ch,self.out_ch), dtype=self.dtype, initializer=kernel_initializer, trainable=self.trainable )
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1572, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1315, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 569, in get_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 521, in _true_getter
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 940, in _get_single_variable
    aggregation=aggregation)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2613, in default_variable_creator
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1668, in __init__
    shape=shape)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1798, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 909, in <lambda>
    partition_info=partition_info)
  File "run/media/user/Flashie/DeepFaceLab_Linux/DeepFaceLab/core/leras/initializers/__init__.py", line 13, in __call__
    return tf.zeros( shape, dtype=dtype, name="_cai_")
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2747, in wrapped
    tensor = fun(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2806, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 239, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3412, in fill
    "Fill", dims=dims, value=value, name=name)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "home/user/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

any help is appreciated. I see on iperovs repo some 3080 users having similar problems, but those are on windows, and I have a 166TI.

**Comment by nagadit** [comment]
You have problem with your GPU driver. Check it or. try reinstall with cudnn

**Comment by Crashhop** [comment]
> You have problem with your GPU driver. Check it or. try reinstall with cudnn

reinstall the OS GPU driver or cudnn from within the env?

**Comment by nagadit** [comment]
Did you do this?

**Comment by Crashhop** [comment]
yes, the enviornment is created acording to the instructions.

**Comment by nagadit** [comment]
Check cudnn and cudatoolkit for your Graphic Card. https://forums.developer.nvidia.com/t/cuda-10-1-and-gtx-1660-ti-not-compatible/79704

**Comment by Crashhop** [comment]
> Check cudnn and cudatoolkit for your Graphic Card. https://forums.developer.nvidia.com/t/cuda-10-1-and-gtx-1660-ti-not-compatible/79704

The GPU driiver doesnt seem to be the problem. other applications run fine on the GPU.. should I downgrade cuda or something? does the env cuda hae to matc the OS version or something? everything seems to be in order, I'm not sure what the problem is.

**Comment by nagadit** [comment]
try run script like 

`bash 6_train_SAEHD.sh`

**Comment by Crashhop** [comment]
> bash 6_train_SAEHD.sh

worked. thanks a ton

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved
