### ISSUE TITLE
can not assign GPU device for operation 

### ISSUE THREAD

**Issue by mostafakhaki** [nagadit/DeepFaceLab_Linux#20]
I have used your instruction to install 'deepfacelab' on my computer,
everything is ok until I want to run this file: '5_XSEG_train.sh'
it detects my GPU device as '[0] GeForce GTX 1080 ti' and I select this device to execute the process, but the following error occurs after running the code.

I'm using the following packages and devices:
CUDA11.1
GPU 1080 ti 11 GIG
Ubuntu 18.04

Error: Cannot assign a device for operation XSeg/conv01/conv/weight: node XSeg/conv01/conv/weight (defined at media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py:76)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]
Traceback (most recent call last):
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation XSeg/conv01/conv/weight: {{node XSeg/conv01/conv/weight}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 17, in __init__
    super().__init__(*args, force_model_class_name='XSeg', **kwargs)
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 68, in on_initialize
    data_format=nn.data_format)
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/facelib/XSegNet.py", line 68, in __init__
    do_init = not model.load_weights( model_file_path )
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Saveable.py", line 96, in load_weights
    nn.batch_set_value(tuples)
  File "/media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py", line 29, in batch_set_value
    nn.tf_sess.run(assign_ops, feed_dict=feed_dict)
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/mosi/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation XSeg/conv01/conv/weight: node XSeg/conv01/conv/weight (defined at media/mosi/0D10-9619/DeepFaceLab/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py:76)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]

**Comment by Crashhop** [comment]
iperov updated the core and it doesnt work on linux anymore using nagadit's instructions. use this command instead to create the environment:

conda create -n deepfacelab -c main python=3.7 cudnn=7.6.5 cudatoolkit=10.1.243

and then downgrade tensorflow-gpu to 2.3.1

python -m pip install tensorflow-gpu==2.3.1

it should now work

**Comment by mostafakhaki** [comment]
Thanks, it works for me.

I use the following packages:
cudatoolkit=10.1.243
python=3.7
cudnn=7.6.5
tqdm
numpy==1.16.0
h5py==2.10.0
opencv-python==4.1.0.25
ffmpeg-python==0.1.17
scikit-image==0.14.2
scipy==1.4.1
colorama
tensorflow-gpu==2.3.1
pyqt5

**Comment by TroyHernandez** [comment]
numpy == 1.16.1

[1.16 has a memory leak](https://github.com/iperov/DeepFaceLab/issues/116).

**Comment by YoochanMyung** [comment]
OS: Ubuntu 20.04
NVIDIA-Driver : 510.47.03
CUDA version: 11.6
GPU: 3090Ti

The following settings work for the above environment.

> conda create -n deepfacelab -c main python=3.7 cudnn=8 cudatoolkit=11
> conda activate deepfacelab
> python -m pip install -r ./DeepFaceLab/requirements-cuda.txt
 

> [requirements-cuda.txt]
> tqdm
> numpy==1.19.3
> numexpr
> h5py==3.1.0
> opencv-python==4.1.0.25
> ffmpeg-python==0.1.17
> scikit-image==0.14.2
> scipy==1.4.1
> colorama
> tensorflow-gpu==2.5.0
> pyqt5
> tf2onnx==1.8.4*

**Comment by Flatheadman** [comment]
It's not just always downgrade. sometimes you need upgrade.
My cuda 11.3 version needs a tensorflow 2.6.0 to use gpu.
Check your proper version from the table here: https://www.tensorflow.org/install/source

**Comment by musketeer38** [comment]
> OS: Ubuntu 20.04 NVIDIA-Driver : 510.47.03 CUDA version: 11.6 GPU: 3090Ti
> 
> The following settings work for the above environment.
> 
> > conda create -n deepfacelab -c main python=3.7 cudnn=8 cudatoolkit=11
> > conda activate deepfacelab
> > python -m pip install -r ./DeepFaceLab/requirements-cuda.txt
> 
> > [requirements-cuda.txt]
> > tqdm
> > numpy==1.19.3
> > numexpr
> > h5py==3.1.0
> > opencv-python==4.1.0.25
> > ffmpeg-python==0.1.17
> > scikit-image==0.14.2
> > scipy==1.4.1
> > colorama
> > tensorflow-gpu==2.5.0
> > pyqt5
> > tf2onnx==1.8.4*

Thanks!! this procedure worked for me. With the original instructions, my GPU was not seen.
I just removed the specific version for tf2onnx.

My env:
HW: AMD Ryzen 5, Nvidia RTX 3060 laptop
SW: Ubuntu 22.04, Nvidia Driver Version: 515.65.01, CUDA Version: 11.7

**Comment by eliliam** [comment]
@YoochanMyung Conda doesn't seem to have opencv-python==4.1.0.25, should I install the latest version of opencb-python(4.6.0.66) instead?
