### ISSUE TITLE
Error pretraining with CelebA

### ISSUE THREAD

**Issue by truenitemarez** [nagadit/DeepFaceLab_Linux#55]
I ran the 4.1_download_CelebA.sh script and have a pretrain_CelebA folder inside DeepFaceLab, and the faceset.pak inside that. However when I try to train and select pretraining on, it says 
```
[y] Enable pretraining mode ( y/n ?:help ) : 
y
Initializing models: 100%|#####################################################################################################################################################################################| 5/5 [00:02<00:00,  2.25it/s]
Loading samples: 0it [00:00, ?it/s]
Error: No training data provided.
Traceback (most recent call last):
  File "/home/user1/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 106, in trainerThread
    debug=debug)
  File "/home/user1/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 246, in __init__
    self.on_initialize()
  File "/home/user1/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 853, in on_initialize
    generators_count=src_generators_count
  File "/home/user1/DeepFaceLab_Linux/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 48, in __init__
    raise ValueError('No training data provided.')
ValueError: No training data provided.
```

How can I pretrain the model?

**Comment by aravindcheruvu** [comment]
This issue is still persistent. Can this be fixed in this clone?
