### ISSUE TITLE
preview during training and interactive merger missing Linux

### ISSUE THREAD

**Issue by princessArthuria** [nagadit/DeepFaceLab_Linux#63]
I'm using the linux implementation, just downloaded the repo yesterday.
When I run training script I don't get a preview window of the training process (no I am not using the "no preview" version of
the script). Also, this might be an issue with the machine I am running this on, but when I press enter the script doesn't 
quit training. 
Similarly, When I run the 7_merge_Quick96.sh script, I don't get the use interactive merger option. 
I checked online and there seems to be at least as of Jan 2022 someone who posted a video using Linux and where
the preview during training and the interactive merger was an option.

Have these features been removed in an update or put somewhere else?

**Comment by zabique** [comment]
[FIX by Dodo] If you run LINUX version of DFL, training started, but there is no training preview then edit:
DeepFaceLab/core/interact/interact.py
last lines of the file, change it to that:
![image_2022-07-02_002718447](https://user-images.githubusercontent.com/58276510/176977366-cab96f87-bfa0-4809-afce-bb857adf0c6b.png)

**Comment by zabique** [comment]
[interact.zip](https://github.com/nagadit/DeepFaceLab_Linux/files/9032072/interact.zip)

**Comment by Kwakyejin** [comment]
Even though I tried change it, nothing changed..
And I got this error
Traceback (most recent call last):
  File "./DeepFaceLab/main.py", line 6, in <module>
    from core.leras import nn
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/leras/nn.py", line 26, in <module>
    from core.interact import interact as io
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/interact/__init__.py", line 1, in <module>
    from .interact import interact
ImportError: cannot import name 'interact' from 'core.interact.interact' (/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/interact/interact.py)

**Comment by zabique** [comment]
scrap that env and use this one

7. conda create -n deepfacelab -c main python=3.7 cudnn=8.2.1 cudatoolkit=11.3.1
8. conda activate deepfacelab
9. Navigate to folder in which u want to install Deepfacelab
10. git clone --depth 1 https://github.com/nagadit/DeepFaceLab_Linux.git
11. cd DeepFaceLab_Linux
**12. git clone --depth 1 https://github.com/MachineEditor/DeepFaceLab.git**
13. python -m pip install -r ./DeepFaceLab/requirements-cuda.txt
14. python -m pip install ffmpeg

**Comment by Kwakyejin** [comment]
> * conda create -n deepfacelab -c main python=3.7 cudnn=8.2.1 cudatoolkit=11.3.1
> * conda activate deepfacelab
> * Navigate to folder in which u want to install Deepfacelab
> * git clone --depth 1 https://github.com/nagadit/DeepFaceLab_Linux.git
> * cd DeepFaceLab_Linux
>   **12. git clone --depth 1 https://github.com/MachineEditor/DeepFaceLab.git**
> * python -m pip install -r ./DeepFaceLab/requirements-cuda.txt
> * python -m pip install ffmpeg

I did it but same error came out...ㅠㅜ

**Comment by Kwakyejin** [comment]
Traceback (most recent call last):
  File "./DeepFaceLab/main.py", line 6, in <module>
    from core.leras import nn
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/leras/nn.py", line 26, in <module>
    from core.interact import interact as io
  File "/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/interact/__init__.py", line 1, in <module>
    from .interact import interact
ImportError: cannot import name 'interact' from 'core.interact.interact' (/home/ng4812/DeepFaceLab_Linux/DeepFaceLab/core/interact/interact.py)

**Comment by zabique** [comment]
strange, seems like you run old env or something. Machine Editor fork never gave me and problems.

**Comment by Kwakyejin** [comment]
I was wondering that what you said above and file that you upload is different. What is correct? Because in file there is if ~~colab: interact = InteractColab() smt..

**Comment by zabique** [comment]
with full MVE fork install, you don't have to do anything with that file. Preview should just work as is. File edit is for Vanilla DFL.

**Comment by marshalleq** [comment]
Hang on, there is an MVE fork for linux?  I thought this was just an iperov fork....
Ah just opening my eyes and see your links above - will try that, thanks!

@zabique I've been trying to get this running on 4090 [here](https://github.com/nagadit/DeepFaceLab_Linux/issues/75).  

Your method above works, but doesn't detect my GPU.  Do you know what the story is with a new GPU - do I need to run newer versions of the library, or does the driver take care of all of that?

I get the sense I need to compile my own, but not 100% sure yet.

Thanks for any help.
