### ISSUE TITLE
6_train_SAEHD.sh ----- TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

### ISSUE THREAD

**Issue by Hydrospanning** [nagadit/DeepFaceLab_Linux#80]
I have data_src and data_dst directories of extracted and aligned faces.  When I run 6_train_SAEHD.sh, it starts but immediately crashes with what appears to be an OpenCV call.

```
~/DeepFaceLab_Linux/scripts$ bash ./6_train_SAEHD.sh 
Running trainer.

[new] No saved models found. Enter a name of a new model : 
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 3050 Laptop GPU

[0] Which GPU indexes to choose? : 
0

[0] Autobackup every N hour ( 0..24 ?:help ) : 
0
[n] Write preview history ( y/n ?:help ) : 
n
[0] Target iteration : 
0
[n] Flip SRC faces randomly ( y/n ?:help ) : 
n
[y] Flip DST faces randomly ( y/n ?:help ) : 
y
[8] Batch_size ( ?:help ) : 
8
[128] Resolution ( 64-640 ?:help ) : 
128
[wf] Face type ( h/mf/f/wf/head ?:help ) : 
wf
[liae-ud] AE architecture ( ?:help ) : 
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) : 
256
[64] Encoder dimensions ( 16-256 ?:help ) : 
64
[64] Decoder dimensions ( 16-256 ?:help ) : 
64
[22] Decoder mask dimensions ( 16-256 ?:help ) : 
22
[y] Masked training ( y/n ?:help ) : 
y
[n] Eyes and mouth priority ( y/n ?:help ) : 
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) : 
n
[n] Blur out mask ( y/n ?:help ) : 
n
[y] Place models and optimizer on GPU ( y/n ?:help ) : 
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) : 
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) : 
n
[y] Enable random warp of samples ( y/n ?:help ) : 
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) : 
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) : 
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) : 
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) : 
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) : 
none
[n] Enable gradient clipping ( y/n ?:help ) : 
n
[n] Enable pretraining mode ( y/n ?:help ) : 
n
Initializing models: 100%|#############################################| 5/5 [00:00<00:00,  6.42it/s]
Loading samples: 100%|#########################################| 1961/1961 [00:01<00:00, 1323.76it/s]
Process Process-15:
Traceback (most recent call last):
  File "/home/mymachine/DeepFaceLab_Linux/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/home/mymachine/DeepFaceLab_Linux/DeepFaceLab/samplelib/SampleProcessor.py", line 106, in process
    warp_params = imagelib.gen_warp_params(resolution,
  File "/home/mymachine/DeepFaceLab_Linux/DeepFaceLab/core/imagelib/warp.py", line 146, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type
```

**Comment by wagyus** [comment]
Edit ```DeepFaceLab_Linux/DeepFaceLab/core/imagelib/warp.py```

At Line 146, change from:
```random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)```
to:
```random_transform_mat = cv2.getRotationMatrix2D((w // 2.0, w // 2.0), rotation, scale)```

Reference from here:
https://github.com/chychkan/DeepFaceLab_MacOS/issues/72
