### ISSUE TITLE
Tensorflow issue

### ISSUE THREAD

**Issue by odt2019** [nagadit/DeepFaceLab_Linux#9]
I'm using Linux Mint 20.

My issue is with tensorflow.
Conda by default installs tensorflow2.2 which doesn't work with the dst face extract script and returns this error.

`AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'`

Downgrading tensorflow to 1.9 works with the dst face extract script but returns the following error with train SAEHD sript.
```
Error: module 'tensorflow.initializers' has no attribute 'glorot_uniform'
Traceback (most recent call last):
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 239, in on_initialize
    inter_out_ch = self.inter.compute_output_channels ( (nn.floatx, (None,encoder_out_ch)))
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 147, in compute_output_channels
    shape = self.compute_output_shape(shapes)
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 121, in compute_output_shape
    self.build()
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/core/leras/models/ModelBase.py", line 33, in _build_sub
    layer.build_weights()
  File "/home/bertus/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Dense.py", line 45, in build_weights
    kernel_initializer = tf.initializers.glorot_uniform(dtype=self.dtype)
AttributeError: module 'tensorflow.initializers' has no attribute 'glorot_uniform'
```

I tried to downgrade tensorflow more since it seems to be recent changes in the module that's causing this but then i ran into dependancy issue so the best solution seems to be to upgrade the scripts but i have no Python knowledge.

**Comment by nagadit** [comment]
Try to do
`python -m pip install -r ./DeepFaceLab/requirements-cuda.txt`

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved
